output_paths:
  consolidated_data: consolidated_data.json
  dashboards: output
  logs: logs
  report_file: simulation_report.log
scenarios:
  api: scenarios/from_api/api.sumocfg
  osm: scenarios/from_osm/osm.sumocfg
sumo_executable: sumo-gui
traci_port: 8813
traffic_lights:
- id: cluster_10894608836_133531789
  phases: []
- id: cluster_148579251_8084152370
  phases: []
- id: cluster_11166071059_11584897064_1840537640_1840537646
  phases: []
- id: '4717230594'
  phases: []
- id: cluster_4292015232_4292016976_4427155300
  phases: []
- id: '148578688'
  phases: []
- id: cluster_184057841_184058361
  phases: []
- id: '2626998166'
  phases: []
- id: '6758072698'
  phases: []
- id: '133539380'
  phases: []
- id: '446299376'
  phases: []
- id: '5076412027'
  phases: []
- id: '11215456434'
  phases: []
- id: '765184593'
  phases: []
- id: cluster_5529899230_5529899232
  phases: []
- id: cluster_396034747_396034753_5883183452_6929720174
  phases: []
- id: cluster_6042752981_6060994012
  phases: []
- id: cluster_133514243_446304418_6929701996_7927170334
  phases: []
- id: '148577946'
  phases: []
- id: '2493065403'
  phases: []
- id: '6042753185'
  phases: []
- id: '148575335'
  phases: []
- id: cluster_148575328_184049229
  phases: []
- id: cluster_184049288_184049290_445662727
  phases: []
- id: '2332218271'
  phases: []
- id: '4292016979'
  phases: []
- id: '12291892219'
  phases: []
- id: cluster_4715802935_6338439745
  phases: []
- id: '5076412049'
  phases: []
- id: cluster_765184597_8916750668
  phases: []
- id: cluster_1838952197_5076412048
  phases: []
- id: cluster_184052443_184055040_8087668864
  phases: []
- id: '8080490284'
  phases: []
- id: '1840537792'
  phases: []
- id: '5538995525'
  phases: []
- id: cluster_184068791_4367016872
  phases: []
- id: '2212089477'
  phases: []
- id: '148578587'
  phases: []
